[project]
name = "hermes-academic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tavaressan", email = "vitortctavares@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
]

[project.scripts]
hermes-academic = "hermes_academic:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
